# Site settings
author: Justin Breneman
title: A journey through learning Full-stack Web Development
header-img: img/home-bg.png
email: justin.breneman@yahoo.com
copyright_name: Justin Breneman
description: > # this means to ignore newlines until "baseurl:"
  Also my first blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JustinBreneman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
